on:
  push:
    branches:
      - main
jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js & Build
        uses: actions/setup-node@v2
        run: yarn build
